### ISSUE TITLE
有demo吗？希望能把这个sdk用起来

### ISSUE THREAD

**Issue by ithaiq** [l306287405/wechat3rd#1]

**Comment by jiawen-afk** [comment]
[README.md](https://github.com/l306287405/wechat3rd#2%E4%BD%BF%E7%94%A8%E5%BC%95%E5%AF%BC)
已经很详细了，跑一遍第二条的全部内容应该就能明白的。

**Comment by ithaiq** [comment]
> [README.md](https://github.com/l306287405/wechat3rd#2%E4%BD%BF%E7%94%A8%E5%BC%95%E5%AF%BC)
> 已经很详细了，跑一遍第二条的全部内容应该就能明白的。

感谢
