### ISSUE TITLE
GetCodePrivacyInfo: 获得隐私接口检测结果这个接口错了不是post请求是get请求，

### ISSUE THREAD

**Issue by tss-tss** [l306287405/wechat3rd#30]
GetCodePrivacyInfo: 获得隐私接口检测结果这个接口错了不是post请求是get请求，
errcode
: 
43001
errmsg
: 
"require GET method, hint: [1b00760a-e112-438d-990d-acf30af38b8a] rid: 6464d5a9-3c3cb5e9-19df1f18"

**Comment by tss-tss** [comment]
改成这样就对了
// GetCodePrivacyInfo 获得隐私接口检测结果
// https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/code-management/getCodePrivacyInfo.html
func (s *Server) GetCodePrivacyInfo(authorizerAccessToken string) (resp *GetCodePrivacyInfoResp) {
	var (
		u   = WECHAT_API_URL + "/wxa/security/get_code_privacy_info?"
		//req = &struct{}{}
		//req=url.Values{}
	)
	resp = &GetCodePrivacyInfoResp{}
	resp.Err(core.GetRequest(u, core.AuthTokenUrlValues(authorizerAccessToken), resp))
	//resp.Err(core.GetRequest(u, req, resp))
	return
}
已测试过

**Comment by jiawen-afk** [comment]
感谢提供修正.已更新版本.

**Comment by tss-tss** [comment]
已完成
