### ISSUE TITLE
关于wechat3rd.Config.Token

### ISSUE THREAD

**Issue by joy999** [l306287405/wechat3rd#8]
现在代码里的check处理。会强行验证为32长度。其实现在消息的验证Token可以不是32位。这里建议调整下。

**Comment by jiawen-afk** [comment]
感谢反馈, 将与下个版本一起提交.

**Comment by Rebellioncry** [comment]
@l306287405 这个长度的问题还是没有解决啊？我看代码还是要32位长度，导致我这边不好对接啊

**Comment by jiawen-afk** [comment]
@Rebellioncry [https://github.com/l306287405/wechat3rd/tree/v1.7.13](v1.7.13) 已修复该问题, 谢谢反馈

**Comment by Rebellioncry** [comment]
@l306287405 好的，看到了，谢谢

**Comment by joy999** [comment]
我可以把我本地的修改回退了。之前一直是使用的修改过的版本。
