### ISSUE TITLE
关于小程序码和小程序二维码的问题

### ISSUE THREAD

**Issue by Rebellioncry** [l306287405/wechat3rd#9]
1.无限制小程序码还缺了几个参数，你现在的无限制小程序码接口的参数其实是有限制的那个接口，详情见官方文档
https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/qrcode-link/qr-code/getUnlimitedQRCode.html
https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/qrcode-link/qr-code/getQRCode.html
2.小程序二维码不打算实现了吗？

**Comment by jiawen-afk** [comment]
@Rebellioncry 好的,我记录下,近期因为找工作学习分布式理论,有些焦头烂额,最迟于下周周末实现上面这两个接口,你如果着急的话可以提Pull requests贡献代码.

**Comment by Rebellioncry** [comment]
有空的话我试试

**Comment by Rebellioncry** [comment]
我提交了一个你有空看看吧

**Comment by jiawen-afk** [comment]
@Rebellioncry 感谢你的贡献 :) ,已经提交新的版本[v1.7.14](https://github.com/l306287405/wechat3rd/tree/v1.7.14)
